language: node_js
node_js:
- node
script:
- yarn generate
- printf 'martinmetodiev.com' > dist/CNAME
- cp 'README.md' dist
env:
  global:
  - secure: "ekbgaJ+yAOWR6t5vlxLcR36Dy03Gv/okkYVQm0cwlMKMxfdSZZQAxFMNDelUvuUBbDWrE/XU3UraUTf3iE9Ev6GlJuFcGCspA6XjPnB6gke/DHebWA5NrXQNVvR6YLWwsB1ZMAVJbuDqOkEbw1VWuyYI5C4tr8sc1uxBmzZeUqc0ZlXTnWusm5D8yNIkAkZww26ZDWHkhatT2ODytH2IbbVuMAk5G1i1Laqz0tQ1qgh92mPV6l+2chWjCsnnBeLlfpUqwKDZPdXCfCW0C4d7J+G5ouGZxADawm6yXJ7CjeFLKEXg4nJAUcqB6drz8NXQqV0dCIRUMNReeF5Vhc45xM7GkthieRrgv1SJXIt4TpAxtlXc1NAhqcgPBpHeYAniclp5Kgk26bACvIO49H8Of1IlxQIiCdPfoyFTKmmhsMj3cVJdxp2CN/5Lcb/riL/6kyKLbM03po8fbddvSW8b76oB6ThhY91KKPihnzEDt7JSYKl3z/UbYn9nF88DRI8Bsyb4w67vLz/wCRoMDA73KLLmqCxXAbYfBM3ghZLOA/m2m2givAW1ayu9FbAHeI+UwJV4i42xrUkfSip9h1RU7NqG/JgV8IrzfhuPjBRDRg0lkmY+SroQ8MPVfUGqN0X5MUiisFhwogYfJ1ieO2CIZGOLunx/y7fEOdhSIj1eZb4="
  - secure: "df/sH4ThU4Lto9m26bL2lqRtcEOT2rv0PUte6ssNhk8Kn7UTdQ/tcJ9u4UAY7nPnquHQ74vgZdqq9D8U7g1CanEaqhPiXOq1EiUoph3ei6aMDms7epFJMvSqYyToPMFVdmczK0nd9ImNw5+/cU9+pTk4uJJ40rfyqnTwCWASk3KM2UIwEI8PKWEB+jIXS8rNSxcnOeK7bf34jdxuHKLjsSVzWTxE95LK7dRm11zFr125x9Tul/AW1FtkfXTZ+K9dqfBH5RH3/Y5iOtbyhdPosTGg13gnrdXYLR9mGtsBILSLz6DjYPQxuwxVdqGqqLJG9LC969MkHtpS98h4z7gjV9Wb/GQWp8lq9G965xsWLHhTe6MWe0Ar9vuo0RQmTPe6MVSHjAmG0UYe9MIAMA+u4s6wEoDBwTRUFKcJpGhVe6RgotDrb8s6V7sUjYZnym+3gjfIolVG0P24NXQzIvfFzPT0dOuW07OGMN9mdH5gmDBDAf/f7wCpXZf3cBik57+3K5Zakgrzd2iTltRs7XXGKnE/TvEfCup+BG1R7bMyVOroVn4suiH+O/N94QcKd9C+c3KpBGK0u8DGavqjyB4oPo0gJn063wwaZa/NJCs8NofS8nqpV9Czm9qXhQ0HwUsJvxrMXDllDY7MoQXpfgdeybtBoQmyM1s+zNoSyxnO/BQ="
branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
- provider: releases
  api_key:
    secure: uVZndLvFMgTAfkwHqVhPphP1umGip5Ox0Szi/Gogy4S16ZmvKIlO+SRcIniMOW8qzE2z75fWlkGeoDPLFe/1/nrpiv+TJGirRq4GSBoiTEbuwoKZAUae4sLXtPTAfz1dMA8yxeit+HUy3JzjLjx5QkYt1qx3/m0l7MFx/r78BnPL5xNNCzcnKfsE9wxIEj7BFYKOrwvnlZ2yg80fXdFNIoAnQtWxe0UVWLCY/nM5v/lg+SnD8EwrbMFsYEfSJ+P3HTHUc9sKyFXipOvm1X0qK3Mf1/5af/t2XMnklNxqAZWKJGJ7U5LV5k7LssIAZue6FyAGuF5qskmA8rUZoWZOvSEtbXDeSd5dZlfTEo9UTivw4L48F0NTh3WeLyfJ0p1WI/9anq8sceoJ7cE9Dlk/oTUaA8Kp5lLX6yGMPkFDU0lcjP0BNLFKCabjGnENLeFsxLLC9UM4v6fW9a4dYcn8dqUQsxjzaKNJqJnGt2CHLWU3yzNJ2KDupE9myf6XNetml12Vl67oxqo5mytn8bgiel7uUNpKRkk65snBHvViKR6BzzoleGurhrpKHZkEmeJJasKtc/u4z79FOZGyP8IUcbGBUemrGRPwrUZ1+6ccyvgY4K9CFAP1Q59pj5DZLth3pHinU/yOxnZ+9N3wnHb0Ke3ddLwN7aVGGICfsJt8ueI=
  skip_cleanup: true
  on:
    tags: true
- provider: pages
  skip_cleanup: true
  local_dir: dist
  target_branch: master
  github_token:
    secure: uVZndLvFMgTAfkwHqVhPphP1umGip5Ox0Szi/Gogy4S16ZmvKIlO+SRcIniMOW8qzE2z75fWlkGeoDPLFe/1/nrpiv+TJGirRq4GSBoiTEbuwoKZAUae4sLXtPTAfz1dMA8yxeit+HUy3JzjLjx5QkYt1qx3/m0l7MFx/r78BnPL5xNNCzcnKfsE9wxIEj7BFYKOrwvnlZ2yg80fXdFNIoAnQtWxe0UVWLCY/nM5v/lg+SnD8EwrbMFsYEfSJ+P3HTHUc9sKyFXipOvm1X0qK3Mf1/5af/t2XMnklNxqAZWKJGJ7U5LV5k7LssIAZue6FyAGuF5qskmA8rUZoWZOvSEtbXDeSd5dZlfTEo9UTivw4L48F0NTh3WeLyfJ0p1WI/9anq8sceoJ7cE9Dlk/oTUaA8Kp5lLX6yGMPkFDU0lcjP0BNLFKCabjGnENLeFsxLLC9UM4v6fW9a4dYcn8dqUQsxjzaKNJqJnGt2CHLWU3yzNJ2KDupE9myf6XNetml12Vl67oxqo5mytn8bgiel7uUNpKRkk65snBHvViKR6BzzoleGurhrpKHZkEmeJJasKtc/u4z79FOZGyP8IUcbGBUemrGRPwrUZ1+6ccyvgY4K9CFAP1Q59pj5DZLth3pHinU/yOxnZ+9N3wnHb0Ke3ddLwN7aVGGICfsJt8ueI=
  on:
    tags: true
