language: node_js
node_js:
- 10
script:
- yarn generate
- printf 'metodiev.dev' > dist/CNAME
- cp 'README.md' dist
before_install:
  - openssl aes-256-cbc -K $encrypted_57f086f95ca1_key -iv $encrypted_57f086f95ca1_iv -in .env.enc -out .env -d
branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
- provider: releases
  api_key:
    secure: uVZndLvFMgTAfkwHqVhPphP1umGip5Ox0Szi/Gogy4S16ZmvKIlO+SRcIniMOW8qzE2z75fWlkGeoDPLFe/1/nrpiv+TJGirRq4GSBoiTEbuwoKZAUae4sLXtPTAfz1dMA8yxeit+HUy3JzjLjx5QkYt1qx3/m0l7MFx/r78BnPL5xNNCzcnKfsE9wxIEj7BFYKOrwvnlZ2yg80fXdFNIoAnQtWxe0UVWLCY/nM5v/lg+SnD8EwrbMFsYEfSJ+P3HTHUc9sKyFXipOvm1X0qK3Mf1/5af/t2XMnklNxqAZWKJGJ7U5LV5k7LssIAZue6FyAGuF5qskmA8rUZoWZOvSEtbXDeSd5dZlfTEo9UTivw4L48F0NTh3WeLyfJ0p1WI/9anq8sceoJ7cE9Dlk/oTUaA8Kp5lLX6yGMPkFDU0lcjP0BNLFKCabjGnENLeFsxLLC9UM4v6fW9a4dYcn8dqUQsxjzaKNJqJnGt2CHLWU3yzNJ2KDupE9myf6XNetml12Vl67oxqo5mytn8bgiel7uUNpKRkk65snBHvViKR6BzzoleGurhrpKHZkEmeJJasKtc/u4z79FOZGyP8IUcbGBUemrGRPwrUZ1+6ccyvgY4K9CFAP1Q59pj5DZLth3pHinU/yOxnZ+9N3wnHb0Ke3ddLwN7aVGGICfsJt8ueI=
  skip_cleanup: true
  on:
    tags: true
- provider: pages
  skip_cleanup: true
  local_dir: dist
  target_branch: master
  github_token:
    secure: uVZndLvFMgTAfkwHqVhPphP1umGip5Ox0Szi/Gogy4S16ZmvKIlO+SRcIniMOW8qzE2z75fWlkGeoDPLFe/1/nrpiv+TJGirRq4GSBoiTEbuwoKZAUae4sLXtPTAfz1dMA8yxeit+HUy3JzjLjx5QkYt1qx3/m0l7MFx/r78BnPL5xNNCzcnKfsE9wxIEj7BFYKOrwvnlZ2yg80fXdFNIoAnQtWxe0UVWLCY/nM5v/lg+SnD8EwrbMFsYEfSJ+P3HTHUc9sKyFXipOvm1X0qK3Mf1/5af/t2XMnklNxqAZWKJGJ7U5LV5k7LssIAZue6FyAGuF5qskmA8rUZoWZOvSEtbXDeSd5dZlfTEo9UTivw4L48F0NTh3WeLyfJ0p1WI/9anq8sceoJ7cE9Dlk/oTUaA8Kp5lLX6yGMPkFDU0lcjP0BNLFKCabjGnENLeFsxLLC9UM4v6fW9a4dYcn8dqUQsxjzaKNJqJnGt2CHLWU3yzNJ2KDupE9myf6XNetml12Vl67oxqo5mytn8bgiel7uUNpKRkk65snBHvViKR6BzzoleGurhrpKHZkEmeJJasKtc/u4z79FOZGyP8IUcbGBUemrGRPwrUZ1+6ccyvgY4K9CFAP1Q59pj5DZLth3pHinU/yOxnZ+9N3wnHb0Ke3ddLwN7aVGGICfsJt8ueI=
  on:
    tags: true
